export const supaBaseUrl = "https://xlljrtxdeirlipgxfsnr.supabase.co";

export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbGpydHhkZWlybGlwZ3hmc25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc2Njc3OTYsImV4cCI6MjA0MzI0Mzc5Nn0.jc3DQ79s--pp5enpUsHLqfe-Ytl6QcXbk0dEG52vKmc";
